In [4]:
import pandas as pd

df = pd.read_csv("credit_risk_dataset.csv")
df.head(16)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
5,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
6,26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3
7,24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4
8,24,83000,RENT,8.0,PERSONAL,A,35000,8.90,1,0.42,N,2
9,21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3
10,22,85000,RENT,6.0,VENTURE,B,35000,10.37,1,0.41,N,4
11,21,10000,OWN,2.0,HOMEIMPROVEMENT,A,4500,8.63,1,0.45,N,2
12,23,95000,RENT,2.0,VENTURE,A,35000,7.90,1,0.37,N,2
13,26,108160,RENT,4.0,EDUCATION,E,35000,18.39,1,0.32,N,4
14,23,115000,RENT,2.0,EDUCATION,A,35000,7.90,0,0.30,N,4
15,23,500000,MORTGAGE,7.0,DEBTCONSOLIDATION,B,30000,10.65,0,0.06,N,3

In [5]:
dummies = pd.get_dummies(df.person_home_ownership)
dummies

       MORTGAGE  OTHER    OWN   RENT
0         False  False  False   True
1         False  False   True  False
2          True  False  False  False
3         False  False  False   True
4         False  False  False   True
...         ...    ...    ...    ...
32576      True  False  False  False
32577      True  False  False  False
32578     False  False  False   True
32579      True  False  False  False
32580     False  False  False   True

[32581 rows x 4 columns]

In [6]:
dummies = pd.get_dummies(df.person_home_ownership) * 1
dummies

       MORTGAGE  OTHER  OWN  RENT
0             0      0    0     1
1             0      0    1     0
2             1      0    0     0
3             0      0    0     1
4             0      0    0     1
...         ...    ...  ...   ...
32576         1      0    0     0
32577         1      0    0     0
32578         0      0    0     1
32579         1      0    0     0
32580         0      0    0     1

[32581 rows x 4 columns]

In [7]:
merged = pd.concat([df,dummies], axis='columns')
merged

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,MORTGAGE,OTHER,OWN,RENT
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0,0,0,1
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0,0,1,0
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,1,0,0,0
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0,0,0,1
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30,1,0,0,0
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19,1,0,0,0
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28,0,0,0,1
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26,1,0,0,0
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30,0,0,0,1

In [8]:
final = merged.drop(['person_home_ownership', 'OTHER'], axis='columns')
final

,person_age,person_income,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,MORTGAGE,OWN,RENT
0,22,59000,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0,0,1
1,21,9600,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0,1,0
2,25,9600,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,1,0,0
3,23,65500,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0,0,1
4,24,54400,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30,1,0,0
32577,54,120000,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19,1,0,0
32578,65,76000,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28,0,0,1
32579,56,150000,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26,1,0,0
32580,66,42000,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30,0,0,1

In [19]:
dummies = pd.get_dummies(df.loan_intent) * 1
dummies

,DEBTCONSOLIDATION,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE
0,0,0,0,0,1,0
1,0,1,0,0,0,0
2,0,0,0,1,0,0
3,0,0,0,1,0,0
4,0,0,0,1,0,0
...,...,...,...,...,...,...
32576,0,0,0,0,1,0
32577,0,0,0,0,1,0
32578,0,0,1,0,0,0
32579,0,0,0,0,1,0
32580,0,0,0,1,0,0

In [20]:
merged = pd.concat([final,dummies], axis='columns')
merged

,person_age,person_income,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,MORTGAGE,OWN,RENT,DEBTCONSOLIDATION,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE
0,22,59000,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,0,0,1,0,0,0,0,1,0
1,21,9600,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0,1,0,0,1,0,0,0,0
2,25,9600,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,1,0,0,0,0,0,1,0,0
3,23,65500,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,0,0,1,0,0,0,1,0,0
4,24,54400,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30,1,0,0,0,0,0,0,1,0
32577,54,120000,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19,1,0,0,0,0,0,0,1,0
32578,65,76000,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28,0,0,1,0,0,1,0,0,0
32579,56,150000,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26,1,0,0,0,0,0,0,1,0
32580,66,42000,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30,0,0,1,0,0,0,1,0,0

In [21]:
finals = merged.drop(['loan_intent', 'VENTURE'], axis='columns')
finals

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,MORTGAGE,OWN,RENT,DEBTCONSOLIDATION,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL
0,22,59000,123.0,D,35000,16.02,1,0.59,Y,3,0,0,1,0,0,0,0,1
1,21,9600,5.0,B,1000,11.14,0,0.10,N,2,0,1,0,0,1,0,0,0
2,25,9600,1.0,C,5500,12.87,1,0.57,N,3,1,0,0,0,0,0,1,0
3,23,65500,4.0,C,35000,15.23,1,0.53,N,2,0,0,1,0,0,0,1,0
4,24,54400,8.0,C,35000,14.27,1,0.55,Y,4,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,C,5800,13.16,0,0.11,N,30,1,0,0,0,0,0,0,1
32577,54,120000,4.0,A,17625,7.49,0,0.15,N,19,1,0,0,0,0,0,0,1
32578,65,76000,3.0,B,35000,10.99,1,0.46,N,28,0,0,1,0,0,1,0,0
32579,56,150000,5.0,B,15000,11.48,0,0.10,N,26,1,0,0,0,0,0,0,1
32580,66,42000,2.0,B,6475,9.99,0,0.15,N,30,0,0,1,0,0,0,1,0

In [22]:
dummies = pd.get_dummies(df.loan_grade) * 1
dummies

       A  B  C  D  E  F  G
0      0  0  0  1  0  0  0
1      0  1  0  0  0  0  0
2      0  0  1  0  0  0  0
3      0  0  1  0  0  0  0
4      0  0  1  0  0  0  0
...   .. .. .. .. .. .. ..
32576  0  0  1  0  0  0  0
32577  1  0  0  0  0  0  0
32578  0  1  0  0  0  0  0
32579  0  1  0  0  0  0  0
32580  0  1  0  0  0  0  0

[32581 rows x 7 columns]

In [23]:
merged = pd.concat([finals,dummies], axis='columns')
merged

,person_age,person_income,person_emp_length,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,...,HOMEIMPROVEMENT,MEDICAL,PERSONAL,A,B,C,D,E,F,G
0,22,59000,123.0,D,35000,16.02,1,0.59,Y,3,...,0,0,1,0,0,0,1,0,0,0
1,21,9600,5.0,B,1000,11.14,0,0.10,N,2,...,0,0,0,0,1,0,0,0,0,0
2,25,9600,1.0,C,5500,12.87,1,0.57,N,3,...,0,1,0,0,0,1,0,0,0,0
3,23,65500,4.0,C,35000,15.23,1,0.53,N,2,...,0,1,0,0,0,1,0,0,0,0
4,24,54400,8.0,C,35000,14.27,1,0.55,Y,4,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,C,5800,13.16,0,0.11,N,30,...,0,0,1,0,0,1,0,0,0,0
32577,54,120000,4.0,A,17625,7.49,0,0.15,N,19,...,0,0,1,1,0,0,0,0,0,0
32578,65,76000,3.0,B,35000,10.99,1,0.46,N,28,...,1,0,0,0,1,0,0,0,0,0
32579,56,150000,5.0,B,15000,11.48,0,0.10,N,26,...,0,0,1,0,1,0,0,0,0,0
32580,66,42000,2.0,B,6475,9.99,0,0.15,N,30,...,0,1,0,0,1,0,0,0,0,0

In [24]:
DropG = merged.drop(['loan_grade', 'G'], axis='columns')
DropG

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,MORTGAGE,...,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,A,B,C,D,E,F
0,22,59000,123.0,35000,16.02,1,0.59,Y,3,0,...,0,0,0,1,0,0,0,1,0,0
1,21,9600,5.0,1000,11.14,0,0.10,N,2,0,...,1,0,0,0,0,1,0,0,0,0
2,25,9600,1.0,5500,12.87,1,0.57,N,3,1,...,0,0,1,0,0,0,1,0,0,0
3,23,65500,4.0,35000,15.23,1,0.53,N,2,0,...,0,0,1,0,0,0,1,0,0,0
4,24,54400,8.0,35000,14.27,1,0.55,Y,4,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,5800,13.16,0,0.11,N,30,1,...,0,0,0,1,0,0,1,0,0,0
32577,54,120000,4.0,17625,7.49,0,0.15,N,19,1,...,0,0,0,1,1,0,0,0,0,0
32578,65,76000,3.0,35000,10.99,1,0.46,N,28,0,...,0,1,0,0,0,1,0,0,0,0
32579,56,150000,5.0,15000,11.48,0,0.10,N,26,1,...,0,0,0,1,0,1,0,0,0,0
32580,66,42000,2.0,6475,9.99,0,0.15,N,30,0,...,0,0,1,0,0,1,0,0,0,0

In [25]:
import pandas as pd

dummies = pd.get_dummies(df.cb_person_default_on_file) * 1
dummies

       N  Y
0      0  1
1      1  0
2      1  0
3      1  0
4      0  1
...   .. ..
32576  1  0
32577  1  0
32578  1  0
32579  1  0
32580  1  0

[32581 rows x 2 columns]

In [26]:
merged = pd.concat([DropG,dummies], axis='columns')
merged

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,MORTGAGE,...,MEDICAL,PERSONAL,A,B,C,D,E,F,N,Y
0,22,59000,123.0,35000,16.02,1,0.59,Y,3,0,...,0,1,0,0,0,1,0,0,0,1
1,21,9600,5.0,1000,11.14,0,0.10,N,2,0,...,0,0,0,1,0,0,0,0,1,0
2,25,9600,1.0,5500,12.87,1,0.57,N,3,1,...,1,0,0,0,1,0,0,0,1,0
3,23,65500,4.0,35000,15.23,1,0.53,N,2,0,...,1,0,0,0,1,0,0,0,1,0
4,24,54400,8.0,35000,14.27,1,0.55,Y,4,0,...,1,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,5800,13.16,0,0.11,N,30,1,...,0,1,0,0,1,0,0,0,1,0
32577,54,120000,4.0,17625,7.49,0,0.15,N,19,1,...,0,1,1,0,0,0,0,0,1,0
32578,65,76000,3.0,35000,10.99,1,0.46,N,28,0,...,0,0,0,1,0,0,0,0,1,0
32579,56,150000,5.0,15000,11.48,0,0.10,N,26,1,...,0,1,0,1,0,0,0,0,1,0
32580,66,42000,2.0,6475,9.99,0,0.15,N,30,0,...,1,0,0,1,0,0,0,0,1,0

In [27]:
DropG = merged.drop(['cb_person_default_on_file', 'Y'], axis='columns')
DropG

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length,MORTGAGE,OWN,...,HOMEIMPROVEMENT,MEDICAL,PERSONAL,A,B,C,D,E,F,N
0,22,59000,123.0,35000,16.02,1,0.59,3,0,0,...,0,0,1,0,0,0,1,0,0,0
1,21,9600,5.0,1000,11.14,0,0.10,2,0,1,...,0,0,0,0,1,0,0,0,0,1
2,25,9600,1.0,5500,12.87,1,0.57,3,1,0,...,0,1,0,0,0,1,0,0,0,1
3,23,65500,4.0,35000,15.23,1,0.53,2,0,0,...,0,1,0,0,0,1,0,0,0,1
4,24,54400,8.0,35000,14.27,1,0.55,4,0,0,...,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,1.0,5800,13.16,0,0.11,30,1,0,...,0,0,1,0,0,1,0,0,0,1
32577,54,120000,4.0,17625,7.49,0,0.15,19,1,0,...,0,0,1,1,0,0,0,0,0,1
32578,65,76000,3.0,35000,10.99,1,0.46,28,0,0,...,1,0,0,0,1,0,0,0,0,1
32579,56,150000,5.0,15000,11.48,0,0.10,26,1,0,...,0,0,1,0,1,0,0,0,0,1
32580,66,42000,2.0,6475,9.99,0,0.15,30,0,0,...,0,1,0,0,1,0,0,0,0,1

In [28]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
X = ('